apiVersion: route.openshift.io/v1
kind: Route
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: 1-python
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: 1-python
    app.kubernetes.io/part-of: test-app-psturc
  name: 1-python
  namespace: psturc
spec:
  port:
    targetPort: 8080
  tls:
    insecureEdgeTerminationPolicy: Redirect
    termination: edge
  to:
    kind: Service
    name: 1-python
    weight: 100
status: {}
